apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: serving
subjects:
- kind: ServiceAccount
  name: default
  namespace: serving
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
