apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: skipgram-train
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            iam.gke.io/gcp-service-account: "164485441658-compute@developer.gserviceaccount.com"
        spec:
          serviceAccountName: default
          containers:
            - name: pytorch
              image: quangtran1011/training_pipeline:v19
              command: 
                - python
                - -m
                - src.itemtovec
              envFrom:
                - configMapRef:
                    name: kubeflow-config
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
                - name: OMP_NUM_THREADS
                  value: "2"
                - name: MASTER_ADDR
                  value: "skipgram-train-master-0"
                - name: MASTER_PORT
                  value: "23456"
                - name: WORLD_SIZE
                  value: "2"
                - name: RANK
                  value: "0"
              resources:
                limits:
                  memory: "10Gi"
                  cpu: "1"
                requests:
                  memory: "8Gi"
                  cpu: "1"
              volumeMounts:
                - name: data
                  mountPath: /mnt/pvc
                - name: dshm
                  mountPath: /dev/shm
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: skipgram-pvc
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: "2Gi"
                
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            iam.gke.io/gcp-service-account: "164485441658-compute@developer.gserviceaccount.com"
        spec:
          serviceAccountName: default
          containers:
            - name: pytorch
              image: quangtran1011/training_pipeline:v19
              command: 
                - python
                - -m
                - src.itemtovec
              envFrom:
                - configMapRef:
                    name: kubeflow-config
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
                - name: OMP_NUM_THREADS
                  value: "2"
                - name: MASTER_ADDR
                  value: "skipgram-train-master-0"
                - name: MASTER_PORT
                  value: "23456"
                - name: WORLD_SIZE
                  value: "2"
                - name: RANK
                  value: "1"
              resources:
                limits:
                  memory: "10Gi"
                  cpu: "1"
                requests:
                  memory: "8Gi"
                  cpu: "1"
              volumeMounts:
                - name: data
                  mountPath: /mnt/pvc
                - name: dshm
                  mountPath: /dev/shm
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: skipgram-pvc
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: "2Gi"