kltn:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: turing-thought-481409-d8
      dataset: kltn
      keyfile: /var/secrets/google/gcp-key.json
      threads: 4
      timeout_seconds: 300
  target: dev
