kltn:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: turing-thought-481409-d8
      dataset: kltn
      keyfile: /home/quangtran/Documents/KLTN2/secret/turing-thought-481409-d8-a5c14752f4af.json
      threads: 4
      timeout_seconds: 300
  target: dev
