apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pytorchjob-operator
  namespace: kubeflow
rules:
- apiGroups: ["kubeflow.org"]
  resources: ["pytorchjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pytorchjob-operator-binding
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pytorchjob-operator
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow
